export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000/api';
const prefix = API_BASE_URL;

export const API_ENDPOINTS = {
  auth: {
    base: `${prefix}/v1/auth`,
    login: `${prefix}/v1/auth/login`,
    signup: `${prefix}/v1/auth/signup`,
    logout: `${prefix}/v1/auth/logout`,
    refresh: `${prefix}/v1/auth/refresh`,
    me: `${prefix}/v1/auth/me`,
    forgotPassword: `${prefix}/v1/auth/forgot-password`,
    resetPassword: `${prefix}/v1/auth/reset-password`,
  },
  subscription: {
    base: `${prefix}/v1/subscription`,
    plans: `${prefix}/v1/subscription/plans`,
    current: `${prefix}/v1/subscription/current`,
    checkout: `${prefix}/v1/subscription/checkout`,
    cancel: `${prefix}/v1/subscription/cancel`,
    upgrade: `${prefix}/v1/subscription/upgrade`,
    downgrade: `${prefix}/v1/subscription/downgrade`,
    invoices: `${prefix}/v1/subscription/invoices`,
  },
  pricing: {
    plans: `${prefix}/v1/pricing/plans`,
    planDetail: (planId: string) => `${prefix}/v1/pricing/plans/${planId}`,
    billingHistory: `${prefix}/v1/pricing/billing-history`,
  },
  plans: {
    list: `${prefix}/v1/plans`,
  },
  users: {
    session: `${prefix}/v1/users/session`,
  },
  scenes: {
    base: `${prefix}/v1/scenes`,
    list: `${prefix}/v1/scenes`,
    create: `${prefix}/v1/scenes`,
    detail: (id: string) => `${prefix}/v1/scenes/${id}`,
    update: (id: string) => `${prefix}/v1/scenes/${id}`,
    delete: (id: string) => `${prefix}/v1/scenes/${id}`,
    duplicate: (id: string) => `${prefix}/v1/scenes/${id}/duplicate`,
    reorder: `${prefix}/v1/scenes/reorder`,
  },
  assets: {
    base: `${prefix}/v1/assets`,
    list: `${prefix}/v1/assets`,
    upload: `${prefix}/v1/assets/upload`,
    detail: (id: string) => `${prefix}/v1/assets/${id}`,
    update: (id: string) => `${prefix}/v1/assets/${id}`,
    delete: (id: string) => `${prefix}/v1/assets/${id}`,
    stats: `${prefix}/v1/assets/stats`,
  },
  audio: {
    base: `${prefix}/v1/audio`,
    list: `${prefix}/v1/audio`,
    upload: `${prefix}/v1/audio/upload`,
    detail: (id: string) => `${prefix}/v1/audio/${id}`,
    update: (id: string) => `${prefix}/v1/audio/${id}`,
    delete: (id: string) => `${prefix}/v1/audio/${id}`,
    favorite: (id: string) => `${prefix}/v1/audio/${id}/favorite`,
  },
  templates: {
    base: `${prefix}/v1/templates`,
    list: `${prefix}/v1/templates`,
    create: `${prefix}/v1/templates`,
    detail: (id: string) => `${prefix}/v1/templates/${id}`,
    update: (id: string) => `${prefix}/v1/templates/${id}`,
    delete: (id: string) => `${prefix}/v1/templates/${id}`,
    export: (id: string) => `${prefix}/v1/templates/${id}/export`,
    import: `${prefix}/v1/templates/import`,
  },
  export: {
    config: `${prefix}/v1/export/config`,
    scene: (id: string) => `${prefix}/v1/export/scene/${id}`,
    video: `${prefix}/v1/export/video`,
    status: (exportId: string) => `${prefix}/v1/export/status/${exportId}`,
    download: (exportId: string) => `${prefix}/v1/export/download/${exportId}`,
  },
  ai: {
    status: `${prefix}/v1/ai/status`,
    generateImagePrompt: `${prefix}/v1/ai/generate-image-prompt`,
    generateScript: `${prefix}/v1/ai/generate-script`,
    generateVoice: `${prefix}/v1/ai/generate-voice`,
    generateMusic: `${prefix}/v1/ai/generate-music`,
    voices: `${prefix}/v1/ai/voices`,
  },
  fonts: {
    list: `${prefix}/v1/fonts`,
  },
  upload: {
    upload: `${prefix}/v1/upload`,
    delete: `${prefix}/v1/upload`,
  },
  userApiKeys: {
    base: `${prefix}/v1/user/api-keys`,
    list: `${prefix}/v1/user/api-keys`,
    save: `${prefix}/v1/user/api-keys`,
    detail: (id: string) => `${prefix}/v1/user/api-keys/${id}`,
    validate: (id: string) => `${prefix}/v1/user/api-keys/${id}/validate`,
    delete: (id: string) => `${prefix}/v1/user/api-keys/${id}`,
  },
  aiUsage: {
    current: `${prefix}/v1/ai-usage/current`,
    history: `${prefix}/v1/ai-usage/history`,
  },
  roles: {
    base: `${prefix}/v1/roles`,
    list: `${prefix}/v1/roles`,
    create: `${prefix}/v1/roles`,
    detail: (roleId: string) => `${prefix}/v1/roles/${roleId}`,
    update: (roleId: string) => `${prefix}/v1/roles/${roleId}`,
    delete: (roleId: string) => `${prefix}/v1/roles/${roleId}`,
    assign: (roleId: string) => `${prefix}/v1/roles/${roleId}/assign`,
  },
  health: {
    check: `${prefix}/v1/health`,
    version: `${prefix}/v1/version`,
    metrics: `${prefix}/v1/metrics`,
  },
  preview: {
    scene: `${prefix}/v1/preview/scene`,
    complete: `${prefix}/v1/preview/complete`,
    status: (previewId: string) => `${prefix}/v1/preview/status/${previewId}`,
    cancel: (previewId: string) => `${prefix}/v1/preview/cancel/${previewId}`,
  },
  channels: {
    base: `${prefix}/v1/channels`,
    list: `${prefix}/v1/channels`,
    create: `${prefix}/v1/channels`,
    detail: (id: string) => `${prefix}/v1/channels/${id}`,
    update: (id: string) => `${prefix}/v1/channels/${id}`,
    delete: (id: string) => `${prefix}/v1/channels/${id}`,
    archive: (id: string) => `${prefix}/v1/channels/${id}/archive`,
    stats: (id: string) => `${prefix}/v1/channels/${id}/stats`,
    uploadLogo: (id: string) => `${prefix}/v1/channels/${id}/brand-kit/logo`,
  },
  projects: {
    base: `${prefix}/v1/projects`,
    list: (channelId: string) => `${prefix}/v1/channels/${channelId}/projects`,
    create: (channelId: string) => `${prefix}/v1/channels/${channelId}/projects`,
    detail: (id: string) => `${prefix}/v1/projects/${id}`,
    update: (id: string) => `${prefix}/v1/projects/${id}`,
    delete: (id: string) => `${prefix}/v1/projects/${id}`,
    duplicate: (id: string) => `${prefix}/v1/projects/${id}/duplicate`,
    autosave: (id: string) => `${prefix}/v1/projects/${id}/autosave`,
  },
};

export default API_ENDPOINTS;
